---
- name: cisco_sh_ver
  hosts: cisco_routers
  gather_facts: true 
  tasks:
    - name: run show version on remote devices
      ios_command:
        commands:
        - show version       
    - name: show run on remote devices
      become: true
      ios_command:
        commands: 
        - show run