---

- hosts: R6

  gather_facts: false
  connection: network_cli


  tasks:

   - name: read ip interfaces 
     ios_command: 
       commands: show ip interface brief
     register: interface
     
   - debug: msg="{{ interface.stdout_lines }}"

   - name: read config 
     ios_command: 
       commands: show running-config
     register: config
     
   - debug: msg="{{ config.stdout_lines }}"

