---
- hosts: localhost

  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"


   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"


   - name: Print return information from the previous task
     ansible.builtin.debug:
       var: DTG
       verbosity: 2
